"""Initial migration.

Revision ID: 97534af7ae0a
Revises: 794bdeb28c7c
Create Date: 2022-04-15 18:19:38.940385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97534af7ae0a'
down_revision = '794bdeb28c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nationality_nationality_key', 'nationality', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('nationality_nationality_key', 'nationality', ['nationality'])
    # ### end Alembic commands ###
