"""Initial migration.

Revision ID: b7e29ba29f1e
Revises: f00f9993f01f
Create Date: 2022-05-01 14:38:57.865140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e29ba29f1e'
down_revision = 'f00f9993f01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decks', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'profile_id')
    # ### end Alembic commands ###
