"""Initial migration.

Revision ID: f00f9993f01f
Revises: 
Create Date: 2022-05-01 14:38:43.185604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f9993f01f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('in_deck', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_deck'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=64), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('pokemons', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemons'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('pokemons', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemons'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_a_id', sa.Integer(), nullable=True),
    sa.Column('transaction_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_a_id'], ['transactions_a.id'], ),
    sa.ForeignKeyConstraint(['transaction_b_id'], ['transactions_b.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('transactions_b')
    op.drop_table('transactions_a')
    op.drop_table('posts')
    op.drop_table('profiles')
    op.drop_table('pokemons')
    op.drop_table('users')
    op.drop_table('decks')
    # ### end Alembic commands ###
